/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AdminIndexRouteImport } from './routes/admin/index';
import { Route as ClientIndexRouteImport } from './routes/client/index';
import { Route as ClientTopIndexRouteImport } from './routes/client/top/index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any);
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any);
const ClientTopIndexRoute = ClientTopIndexRouteImport.update({
  id: '/client/top/',
  path: '/client/top/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/admin/': typeof AdminIndexRoute;
  '/client/': typeof ClientIndexRoute;
  '/client/top/': typeof ClientTopIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/admin': typeof AdminIndexRoute;
  '/client': typeof ClientIndexRoute;
  '/client/top': typeof ClientTopIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/admin/': typeof AdminIndexRoute;
  '/client/': typeof ClientIndexRoute;
  '/client/top/': typeof ClientTopIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/admin/' | '/client/' | '/client/top/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/admin' | '/client' | '/client/top';
  id: '__root__' | '/' | '/admin/' | '/client/' | '/client/top/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
  ClientIndexRoute: typeof ClientIndexRoute;
  ClientTopIndexRoute: typeof ClientTopIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/': {
      id: '/admin/';
      path: '/admin';
      fullPath: '/admin/';
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/client/': {
      id: '/client/';
      path: '/client';
      fullPath: '/client/';
      preLoaderRoute: typeof ClientIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/client/top/': {
      id: '/client/top/';
      path: '/client/top';
      fullPath: '/client/top/';
      preLoaderRoute: typeof ClientTopIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientTopIndexRoute: ClientTopIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
