/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AdminIndexRouteImport } from './routes/admin/index';
import { Route as ClientIndexRouteImport } from './routes/client/index';
import { Route as ClientPIndexRouteImport } from './routes/client/p/index';
import { Route as ClientTopIndexRouteImport } from './routes/client/top/index';
import { Route as ClientPHandleIndexRouteImport } from './routes/client/p/$handle/index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any);
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any);
const ClientPIndexRoute = ClientPIndexRouteImport.update({
  id: '/client/p/',
  path: '/client/p/',
  getParentRoute: () => rootRouteImport,
} as any);
const ClientTopIndexRoute = ClientTopIndexRouteImport.update({
  id: '/client/top/',
  path: '/client/top/',
  getParentRoute: () => rootRouteImport,
} as any);
const ClientPHandleIndexRoute = ClientPHandleIndexRouteImport.update({
  id: '/client/p/$handle/',
  path: '/client/p/$handle/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/admin/': typeof AdminIndexRoute;
  '/client/': typeof ClientIndexRoute;
  '/client/p/': typeof ClientPIndexRoute;
  '/client/top/': typeof ClientTopIndexRoute;
  '/client/p/$handle/': typeof ClientPHandleIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/admin': typeof AdminIndexRoute;
  '/client': typeof ClientIndexRoute;
  '/client/p': typeof ClientPIndexRoute;
  '/client/top': typeof ClientTopIndexRoute;
  '/client/p/$handle': typeof ClientPHandleIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/admin/': typeof AdminIndexRoute;
  '/client/': typeof ClientIndexRoute;
  '/client/p/': typeof ClientPIndexRoute;
  '/client/top/': typeof ClientTopIndexRoute;
  '/client/p/$handle/': typeof ClientPHandleIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/admin/'
    | '/client/'
    | '/client/p/'
    | '/client/top/'
    | '/client/p/$handle/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/admin'
    | '/client'
    | '/client/p'
    | '/client/top'
    | '/client/p/$handle';
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/client/'
    | '/client/p/'
    | '/client/top/'
    | '/client/p/$handle/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
  ClientIndexRoute: typeof ClientIndexRoute;
  ClientPIndexRoute: typeof ClientPIndexRoute;
  ClientTopIndexRoute: typeof ClientTopIndexRoute;
  ClientPHandleIndexRoute: typeof ClientPHandleIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin/': {
      id: '/admin/';
      path: '/admin';
      fullPath: '/admin/';
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/client/': {
      id: '/client/';
      path: '/client';
      fullPath: '/client/';
      preLoaderRoute: typeof ClientIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/client/p/': {
      id: '/client/p/';
      path: '/client/p';
      fullPath: '/client/p/';
      preLoaderRoute: typeof ClientPIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/client/top/': {
      id: '/client/top/';
      path: '/client/top';
      fullPath: '/client/top/';
      preLoaderRoute: typeof ClientTopIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/client/p/$handle/': {
      id: '/client/p/$handle/';
      path: '/client/p/$handle';
      fullPath: '/client/p/$handle/';
      preLoaderRoute: typeof ClientPHandleIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientPIndexRoute: ClientPIndexRoute,
  ClientTopIndexRoute: ClientTopIndexRoute,
  ClientPHandleIndexRoute: ClientPHandleIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
